# Site settings
title: Genesis -  a tool for data center automation
email: opensourcesoftware@tumblr.com
##  Write an awesome description for your new site here. You can edit this
##  line in _config.yml. It will appear in your document head meta (for
##  Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  Genesis is the system we use to intake new hardware into our
  datacenter. It handles the burn-in, system configuration, and asset
  creation in Collins (our asset tracking system). It is also used by
  our datacenter techs to diagnose hardware issues with new and
  existing hardware.
host: 127.0.0.1
#port: 4000
##baseurl: "" # the subpath of your site, e.g. /blog/
##url: "http://yourdomain.com" # the base hostname & protocol for your site
##twitter_username: jekyllrb
github_username:  tumblr

# Build settings
##markdown: kramdown
exclude:
  - '.gitignore'
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  - '.bundle'
