# Site settings
title: Genesis
email: opensourcesoftware@tumblr.com
##  Write an awesome description for your new site here. You can edit this
##  line in _config.yml. It will appear in your document head meta (for
##  Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
   a tool for data center automation
host: 127.0.0.1
#port: 4000
baseurl: "/genesis"
##url: "http://yourdomain.com" # the base hostname & protocol for your site
##twitter_username: jekyllrb
github_username:  tumblr

# Build settings
markdown: kramdown
exclude:
  - '.gitignore'
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  - '.bundle'
